# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd345c021f2fde682c71376bee0bbcb0acaaa4072d524054072a7980354466729c37ba07814d945fd8bf687e84f77b6bb58a167752d30f34ae50f52ec64782de

test:
  secret_key_base: 62d3265e606cbe208666adc9285150a5452446bd7029f8ab0333266afda63b18df2d3047193307bdd708c31b9f9a54ab89352376759a43d741115b28c337aef0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
